### ISSUE TITLE
Перевод справочника внутреннего сайта на WAP

### ISSUE THREAD

**Issue by GoldMax** [ElectroService/WAP#87]
- [x] Починить отправку уведомлений о новых поручения на почту для Отдела разработки ПО @romult
- [x] архив - по автору - жмем на пользователя
- [ ] Почта админам и весте (ithelp@elektro.ru `DateTime.Now + " УВОЛЕН <br />" + Request["fio"] + "<br />" + "Email: " + Request["email"]`) (ElectroService/SIM#29)  
- [x] Обновить именинников
- [x] Обновить версию весты
- [x] Обновить доски почета
- [x] Убрать ссылку "ТОВАРНЫЕ ЗАПАСЫ" (в старой версии ее небыло)
- [x] Не отображаются новости Весты (ошибка)
- [x] Не работают народные новости
- [ ] Статистика 
- [x] Ссылка "ИЗМЕНЕНИЯ НОМЕНКЛАТУРЫ", в форме отчета можно выбрать период только до 2014-го года.
- [x]   Товар - не показывает -  Выбор необходимой цветности люминесцентной лампы,Tecnoquint - Сечения и наполняемость 
- [x] Значок сотового оператора (добавить отображение на сайте)
- [x] Сплиттеры
- [x] Ограничения панелей по размеру (маленькие мониторы)
- [x] сохранение длинных примечаний

--- Доработки на внутреннем сайте ---
- [x] В поручениях пропала возможность посмотреть карточку сотрудника
- [x] Не работает детальный просмотр поручения
- [x] В архиве при открытии карточки документа в разделе - "Новые поступления", ошибка - Íåäîïóñòèìîå èñïîëüçîâàíèå Null: 'CStr'
/arxiv/asp/cards2.asp, line 55
- [x] При заведении нового сотрудника валидация требует ввести код страны.
- [x] Поручения - поиск в личных заметках
- [x] Поиск по справочнику сотрудников
 
--- После релиза ---
- [x] Переделать телефон (лидирующий ноль в номере телефона не сохраняется) @ElenaKoder
- [ ] Сотрудник без постов, посты без ролей ? (ElectroService/SIM#30)
- [ ] Увольнение сотрудников (ElectroService/SIM#29)
- [x] Обновление списка сотрудников при изменении данных о сотруднике
- [ ] Добавить возможность указывать заместителей  (ElectroService/SIM#31)

- [ ] изменение данных из WAPдолжно кидать уведомление HRM (ElectroService/SIM#24)
- [ ] Безопасность из ролей и подразделений (ElectroService/SIM#1)
